baseURL = "/"
languageCode = 'en-us'
title = 'Sharat Project'
theme = 'onePage'


#################### default parameters ################################
[params]
logo = "images/about-pic-karanas.jpg"
og_image = "images/about-pic-karanas.jpg"
home = "Home"
# Meta data
description = ""
author = "TenSketch"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# copyright
copyright = "| Copyright &copy; 2019 [Gethugothemes](https://gethugothemes.com) All Rights Reserved |"

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/css/main.css"
  
  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/js/main.js"